import type { Recipe } from "@/types/recipe";

const now = new Date().toISOString();

export const DEMO_RECIPES: Recipe[] = [
  {
    id: "d0000000-0000-0000-0000-000000000001",
    name: "Chicken Stir-Fry",
    ingredients: [
      { name: "chicken breast", quantity: "1", unit: "lb" },
      { name: "broccoli", quantity: "2", unit: "cups" },
      { name: "soy sauce", quantity: "3", unit: "tbsp" },
      { name: "garlic", quantity: "3", unit: "cloves" },
      { name: "sesame oil", quantity: "1", unit: "tbsp" },
      { name: "rice", quantity: "2", unit: "cups" },
    ],
    instructions:
      "Cut chicken into strips. Heat sesame oil, cook chicken until golden. Add garlic and broccoli, stir-fry 4 minutes. Add soy sauce. Serve over rice.",
    tags: ["asian", "quick", "high-protein"],
    servings: 4,
    prep_time: 10,
    cook_time: 15,
    source_url: null,
    notes: "Great for weeknights. Can swap broccoli for snap peas.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "d0000000-0000-0000-0000-000000000002",
    name: "Spaghetti Bolognese",
    ingredients: [
      { name: "ground beef", quantity: "1", unit: "lb" },
      { name: "spaghetti", quantity: "1", unit: "lb" },
      { name: "crushed tomatoes", quantity: "28", unit: "oz" },
      { name: "onion", quantity: "1", unit: "medium" },
      { name: "garlic", quantity: "4", unit: "cloves" },
      { name: "olive oil", quantity: "2", unit: "tbsp" },
      { name: "parmesan cheese", quantity: "0.5", unit: "cup" },
    ],
    instructions:
      "Sauté onion and garlic in olive oil. Brown the beef. Add crushed tomatoes, simmer 20 minutes. Cook spaghetti. Serve sauce over pasta with parmesan.",
    tags: ["italian", "comfort-food", "family-favorite"],
    servings: 4,
    prep_time: 10,
    cook_time: 30,
    source_url: null,
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "d0000000-0000-0000-0000-000000000003",
    name: "Black Bean Tacos",
    ingredients: [
      { name: "black beans", quantity: "2", unit: "cans" },
      { name: "corn tortillas", quantity: "12", unit: "" },
      { name: "avocado", quantity: "2", unit: "" },
      { name: "lime", quantity: "2", unit: "" },
      { name: "cilantro", quantity: "1", unit: "bunch" },
      { name: "cumin", quantity: "1", unit: "tsp" },
      { name: "salsa", quantity: "1", unit: "cup" },
    ],
    instructions:
      "Heat beans with cumin. Warm tortillas. Mash avocado with lime juice. Assemble tacos with beans, guacamole, salsa, and cilantro.",
    tags: ["mexican", "vegetarian", "quick"],
    servings: 4,
    prep_time: 10,
    cook_time: 10,
    source_url: null,
    notes: "Kid-friendly if you skip the cilantro.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "d0000000-0000-0000-0000-000000000004",
    name: "Salmon with Roasted Vegetables",
    ingredients: [
      { name: "salmon fillets", quantity: "4", unit: "" },
      { name: "sweet potato", quantity: "2", unit: "large" },
      { name: "brussels sprouts", quantity: "1", unit: "lb" },
      { name: "olive oil", quantity: "3", unit: "tbsp" },
      { name: "lemon", quantity: "1", unit: "" },
      { name: "garlic powder", quantity: "1", unit: "tsp" },
    ],
    instructions:
      "Preheat oven to 400°F. Cube sweet potatoes, halve brussels sprouts, toss with oil and garlic powder. Roast 20 minutes. Add salmon to sheet pan, squeeze lemon over top. Roast 12 more minutes.",
    tags: ["healthy", "sheet-pan", "seafood"],
    servings: 4,
    prep_time: 15,
    cook_time: 32,
    source_url: null,
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "d0000000-0000-0000-0000-000000000005",
    name: "Thai Coconut Curry",
    ingredients: [
      { name: "coconut milk", quantity: "1", unit: "can" },
      { name: "red curry paste", quantity: "2", unit: "tbsp" },
      { name: "chicken thighs", quantity: "1.5", unit: "lbs" },
      { name: "bell pepper", quantity: "2", unit: "" },
      { name: "bamboo shoots", quantity: "1", unit: "can" },
      { name: "fish sauce", quantity: "1", unit: "tbsp" },
      { name: "basil", quantity: "1", unit: "cup" },
      { name: "jasmine rice", quantity: "2", unit: "cups" },
    ],
    instructions:
      "Simmer curry paste in a splash of coconut milk. Add chicken, cook 5 min. Add remaining coconut milk, bell peppers, bamboo shoots, and fish sauce. Simmer 15 min. Stir in basil. Serve over jasmine rice.",
    tags: ["asian", "curry", "gluten-free"],
    servings: 4,
    prep_time: 10,
    cook_time: 25,
    source_url: null,
    notes: "Use tofu instead of chicken for a vegetarian version.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "d0000000-0000-0000-0000-000000000006",
    name: "Caesar Salad with Grilled Chicken",
    ingredients: [
      { name: "romaine lettuce", quantity: "2", unit: "heads" },
      { name: "chicken breast", quantity: "1", unit: "lb" },
      { name: "parmesan cheese", quantity: "0.5", unit: "cup" },
      { name: "croutons", quantity: "1", unit: "cup" },
      { name: "caesar dressing", quantity: "0.5", unit: "cup" },
      { name: "lemon", quantity: "1", unit: "" },
    ],
    instructions:
      "Season and grill chicken breasts 6 min per side. Chop romaine, toss with dressing, parmesan, and croutons. Slice chicken and place on top. Squeeze lemon over salad.",
    tags: ["salad", "healthy", "quick"],
    servings: 4,
    prep_time: 10,
    cook_time: 12,
    source_url: null,
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "d0000000-0000-0000-0000-000000000007",
    name: "Mushroom Risotto",
    ingredients: [
      { name: "arborio rice", quantity: "1.5", unit: "cups" },
      { name: "mixed mushrooms", quantity: "1", unit: "lb" },
      { name: "vegetable broth", quantity: "4", unit: "cups" },
      { name: "white wine", quantity: "0.5", unit: "cup" },
      { name: "parmesan cheese", quantity: "0.5", unit: "cup" },
      { name: "butter", quantity: "2", unit: "tbsp" },
      { name: "shallots", quantity: "2", unit: "" },
    ],
    instructions:
      "Sauté mushrooms in butter, set aside. Sauté shallots, add rice, toast 2 min. Add wine, stir until absorbed. Ladle in broth gradually, stirring often, until rice is creamy (about 18 min). Fold in mushrooms and parmesan.",
    tags: ["italian", "vegetarian", "comfort-food"],
    servings: 4,
    prep_time: 10,
    cook_time: 30,
    source_url: null,
    notes: "Use a mix of cremini, shiitake, and oyster mushrooms for best flavor.",
    created_at: now,
    updated_at: now,
  },
];
