import { getResend } from "@/lib/resend";
import type { MealPlan } from "@/types/meal-plan";

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatWeekOf(weekOf: string): string {
  return new Intl.DateTimeFormat("en-US", { dateStyle: "long" }).format(
    new Date(weekOf + "T00:00:00")
  );
}

export function parseRecipients(envVar: string | undefined): string[] {
  if (!envVar || !envVar.trim()) {
    throw new Error("EMAIL_RECIPIENTS environment variable is required");
  }
  const recipients = envVar
    .split(",")
    .map((e) => e.trim())
    .filter((e) => e.length > 0);
  if (recipients.length === 0) {
    throw new Error("EMAIL_RECIPIENTS environment variable is required");
  }
  return recipients;
}

export function formatMealPlanEmail(plan: MealPlan): {
  subject: string;
  html: string;
  text: string;
} {
  const weekLabel = formatWeekOf(plan.weekOf);
  const subject = `Your Meal Plan for the week of ${weekLabel}`;

  // Plain text version
  const textDinners = plan.dinners
    .map((d) => {
      let line = `${d.day}: ${d.recipeName} (${d.servings} servings)`;
      if (d.alternativeNote) {
        line += `\n  ${d.alternativeNote}`;
      }
      return line;
    })
    .join("\n");

  const textGrocery = plan.groceryList
    .map((g) => `- ${g.item}: ${g.quantity}`)
    .join("\n");

  const text = `${subject}\n\n--- Dinners ---\n\n${textDinners}\n\n--- Grocery List ---\n\n${textGrocery}\n\nGenerated by Meal Assistant`;

  // HTML version
  const dinnerCards = plan.dinners
    .map((d) => {
      const alt = d.alternativeNote
        ? `<p style="margin:4px 0 0;color:#6b7280;font-style:italic;font-size:14px;">${escapeHtml(d.alternativeNote)}</p>`
        : "";
      return `<div style="background:#f9fafb;border-radius:8px;padding:16px;margin-bottom:12px;">
        <div style="font-size:14px;color:#6b7280;margin-bottom:4px;">${escapeHtml(d.day)}</div>
        <div style="font-size:18px;font-weight:600;color:#111827;">${escapeHtml(d.recipeName)}</div>
        <div style="font-size:14px;color:#6b7280;margin-top:4px;">${d.servings} servings</div>${alt}
      </div>`;
    })
    .join("\n");

  const groceryItems = plan.groceryList
    .map(
      (g) =>
        `<li style="padding:4px 0;">${escapeHtml(g.item)} — ${escapeHtml(g.quantity)}</li>`
    )
    .join("\n");

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#ffffff;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:24px;">
    <h1 style="font-size:24px;color:#111827;margin:0 0 24px;">Your Meal Plan for the week of ${escapeHtml(weekLabel)}</h1>
    <h2 style="font-size:18px;color:#374151;margin:0 0 12px;">Dinners</h2>
    ${dinnerCards}
    <h2 style="font-size:18px;color:#374151;margin:24px 0 12px;">Grocery List</h2>
    <ul style="margin:0;padding:0 0 0 20px;color:#111827;">
      ${groceryItems}
    </ul>
    <p style="margin:32px 0 0;font-size:12px;color:#9ca3af;">Generated by Meal Assistant</p>
  </div>
</body>
</html>`;

  return { subject, html, text };
}

export async function sendMealPlanEmail(
  plan: MealPlan
): Promise<{ emailId: string }> {
  const from = process.env.EMAIL_FROM;
  if (!from) {
    throw new Error("EMAIL_FROM environment variable is required");
  }

  const to = parseRecipients(process.env.EMAIL_RECIPIENTS);
  const { subject, html, text } = formatMealPlanEmail(plan);

  const { data, error } = await getResend().emails.send({
    from,
    to,
    subject,
    html,
    text,
  });

  if (error) {
    throw new Error(error.message);
  }

  return { emailId: data!.id };
}
